specVersion: 1.0.0
name: frontier-evm-starter-project
version: 1.0.0
runner:
  node:
    name: "@subql/node-cosmos"
    version: "*"
  query:
    name: "@subql/query"
    version: ">=0.16.0"
description: >-
  A basic Ethermint EVM example project with an event and call handler. Read more about this at https://university.subquery.network/build/substrate-evm.html. This project can be use as a starting point for developing your SubQuery project
repository: https://github.com/subquery/ethermint-evm-starter
schema:
  file: ./schema.graphql
network:
  chainId: "evmos_9001-2" # Genesis hash of Moonriver
  endpoint: "https://rpc-evmos.whispernode.com"
  # Optionally provide the HTTP endpoint of a full chain dictionary to speed up processing
  # dictionary: "https://api.subquery.network/sq/subquery/moonriver-dictionary"
  chainTypes:
    ethermint.evm.v1:
      file: "./proto/ethermint/evm/v1/tx.proto"
      messages:
        - "MsgEthereumTx"
        - "LegacyTx"
        - "AccessListTx"
        - "DynamicFeeTx"
    ethermint.evm.v12:
      file: "./proto/ethermint/evm/v1/evm.proto"
      messages:
        - "AccessTuple"
    google.protobuf:
      file: "./proto/google/protobuf/any.proto"
      messages:
        - "Any"

dataSources:
  - kind: cosmos/EthermintEvm
    startBlock: 1346388
    processor:
      file: "./node_modules/@subql/ethermint-evm-processor/dist/index.js"
      options:
        abi: erc20
        address: "0x1488346419FFc85C6D54E71be80a222971fb2240" # Cronus Finance
    assets:
      erc20:
        file: "./erc20.abi.json"
    mapping:
      file: "./dist/index.js"
      handlers:
        - handler: handleEthermintEvmEvent
          kind: cosmos/EthermintEvmEvent
          filter:
            topics:
              ## Example valid values:
              # - '0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef'
              # - Transfer(address,address,u256)
              # - Transfer(address from,address to,uint256 value)
              - Transfer(address indexed from,address indexed to,uint256 value)
              - null
              - null
              - null
        #- handler: handleEthermintEvmCall
        #  kind: cosmos/EthermintEvmCall
        #  filter:
        #    method: approve(address spender, uint256 amount)
            ## The transaction sender
            # from: "0xcc29d61e6915b42f7c46465dfc854d63218a5d1a"
